sudo: required
services:
  - docker

before_install: 
  - docker build -t phaymanww/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run -e CI=true phaymanww/react-test npm test

after_success:
  - docker build -t phaymanww/multi-client ./client
  - docker build -t phaymanww/multi-nginx ./nginx
  - docker build -t phaymanww/multi-server ./server
  - docker build -t phaymanww/multi-worker ./worker